In [2]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

In [3]:
geo =pd.read_csv('C:/My Folder/UTD/Semester/Spring_2023/BUAN_6341_Applied_Machine_Learning/Regression.csv')
geo

driverid          city  velocity  Total Miles         Model  event_ind  \
0          A1         Aptos        75       628507  Freightliner          0   
1          A1        Oceano        34       628507  Freightliner          0   
2          A1        Gilroy        19       628507  Freightliner          0   
3          A1       Modesto        75       628507  Freightliner          0   
4          A1      Palmdale        55       628507  Freightliner          0   
...       ...           ...       ...          ...           ...        ...   
7995      A99    Santa Rosa        54       640800     Peterbilt          0   
7996      A99    Santa Rosa         0       640800     Peterbilt          0   
7997      A99      Martinez        61       640800     Peterbilt          0   
7998      A99  Apple Valley        90       640800     Peterbilt          1   
7999      A99    Santa Rosa         0       640800     Peterbilt          0   

      Riskfactor  
0       4.773217  
1       4.773217  
2       4.773217  
3       4.773217  
4       4.773217  
...          ...  
7995    6.242197  
7996    6.242197  
7997    6.242197  
7998    6.242197  
7999    6.242197  

[8000 rows x 7 columns]

In [5]:
geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   driverid     8000 non-null   object 
 1   city         8000 non-null   object 
 2   velocity     8000 non-null   int64  
 3   Total Miles  8000 non-null   int64  
 4   Model        8000 non-null   object 
 5   event_ind    8000 non-null   int64  
 6   Riskfactor   8000 non-null   float64
dtypes: float64(1), int64(3), object(3)
memory usage: 437.6+ KB


In [6]:
import pandas as pd
import category_encoders as ce


# create a leave-one-out encoder object
looe = ce.LeaveOneOutEncoder()

# apply target encoding to columns 'col1' and 'col2'
geo[['Model_te', 'driverid_te', 'city_te']] = looe.fit_transform(geo[['Model', 'driverid', 'city']], geo['event_ind'])

# display the encoded dataframe
print(geo)


     driverid          city  velocity  Total Miles         Model  event_ind  \
0          A1         Aptos        75       628507  Freightliner          0   
1          A1        Oceano        34       628507  Freightliner          0   
2          A1        Gilroy        19       628507  Freightliner          0   
3          A1       Modesto        75       628507  Freightliner          0   
4          A1      Palmdale        55       628507  Freightliner          0   
...       ...           ...       ...          ...           ...        ...   
7995      A99    Santa Rosa        54       640800     Peterbilt          0   
7996      A99    Santa Rosa         0       640800     Peterbilt          0   
7997      A99      Martinez        61       640800     Peterbilt          0   
7998      A99  Apple Valley        90       640800     Peterbilt          1   
7999      A99    Santa Rosa         0       640800     Peterbilt          0   

      Riskfactor  Model_te  driverid_te   city_te  

In [7]:
geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   driverid     8000 non-null   object 
 1   city         8000 non-null   object 
 2   velocity     8000 non-null   int64  
 3   Total Miles  8000 non-null   int64  
 4   Model        8000 non-null   object 
 5   event_ind    8000 non-null   int64  
 6   Riskfactor   8000 non-null   float64
 7   Model_te     8000 non-null   float64
 8   driverid_te  8000 non-null   float64
 9   city_te      8000 non-null   float64
dtypes: float64(4), int64(3), object(3)
memory usage: 625.1+ KB


In [8]:
geo.corr().T

C:\Users\prriy\AppData\Local\Temp\ipykernel_16212\1831921642.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  geo.corr().T


velocity  Total Miles  event_ind  Riskfactor  Model_te  \
velocity     1.000000    -0.003717   0.109832    0.007547  0.002914   
Total Miles -0.003717     1.000000  -0.004039   -0.097918 -0.051459   
event_ind    0.109832    -0.004039   1.000000    0.117964 -0.005489   
Riskfactor   0.007547    -0.097918   0.117964    1.000000  0.225078   
Model_te     0.002914    -0.051459  -0.005489    0.225078  1.000000   
driverid_te -0.005885    -0.033117   0.018393    0.967281  0.288602   
city_te      0.000753    -0.014484  -0.018445    0.004756 -0.036687   

             driverid_te   city_te  
velocity       -0.005885  0.000753  
Total Miles    -0.033117 -0.014484  
event_ind       0.018393 -0.018445  
Riskfactor      0.967281  0.004756  
Model_te        0.288602 -0.036687  
driverid_te     1.000000  0.008481  
city_te         0.008481  1.000000

In [9]:
target_col = geo['event_ind']
predictor_cols = geo[[ 'velocity','Riskfactor','Model_te', 'city_te']]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(predictor_cols, target_col, test_size=0.2, random_state=1)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# scale the data
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_train

array([[ 0.07187392,  0.06014102,  0.85908026, -0.39865445],
       [-0.6514488 ,  0.14106605,  0.85908026,  0.05261797],
       [-0.12904906,  0.1530416 , -0.94572951, -0.31408367],
       ...,
       [ 1.39796556,  0.16515818, -1.29388359, -1.75231607],
       [-1.41495611, -0.19960563,  0.85908026, -0.25693536],
       [-1.41495611, -0.23280883, -0.08824047, -0.19462783]])

In [10]:
# Training the Logistic Regression model on the Training set

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
result = classifier.fit(X_train, y_train)

In [11]:
# Predicting the Test set results

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.to_numpy().reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [12]:
# Making the confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1506    2]
 [  92    0]]


0.94125

In [14]:
# import the necessary libraries
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm

# define the list of coefficients
coefficients = ['velocity', 'Riskfactor', 'Model_te', 'city_te']

# create and train a logistic regression model
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

# get the coefficients and intercept for the trained model
coef = logreg.coef_
intercept = logreg.intercept_

# fit the logistic regression model using statsmodels to get the p-values
logit_model = sm.Logit(y_train, X_train)
result = logit_model.fit()

# loop through the list of coefficients and print the relevant information
for i in range(len(coefficients)):
    print("p-value for {}: {}".format(coefficients[i], result.pvalues[i]))

print("\n")

# loop through the list of coefficients and print the relevant information
for i in range(len(coefficients)):
    print("Coefficient for {}: {}".format(coefficients[i], coef[0][i]))

print("\n")

# loop through the list of coefficients and print the relevant information
for i in range(len(coefficients)):
    print("Exp of Coefficient for {}: {}".format(coefficients[i], np.exp(coef[0][i])))

print("\n")

# loop through the list of coefficients and print the relevant information
for i in range(len(coefficients)):
    if i >= 2:
        print("1/Exp of Coefficient for {}: {}".format(coefficients[i], 1/np.exp(coef[0][i])))

# print the intercept
print("\nIntercept:", intercept)


Optimization terminated successfully.
         Current function value: 0.689809
         Iterations 4
p-value for velocity: 3.9340052017827145e-05
p-value for Riskfactor: 9.054618848700398e-07
p-value for Model_te: 0.16678496686580324
p-value for city_te: 0.4028257250662143


Coefficient for velocity: 0.5138237126017503
Coefficient for Riskfactor: 0.3710763054853944
Coefficient for Model_te: -0.0815889724131506
Coefficient for city_te: -0.09052788355771847


Exp of Coefficient for velocity: 1.6716709793314448
Exp of Coefficient for Riskfactor: 1.4492936582235458
Exp of Coefficient for Model_te: 0.9216507047185631
Exp of Coefficient for city_te: 0.9134488633417458


1/Exp of Coefficient for Model_te: 1.08500974922529
1/Exp of Coefficient for city_te: 1.0947520327975635

Intercept: [-3.0098931]


In [ ]:
import statsmodels.api as sm

y = geo['event_ind']
X = geo[['velocity','Riskfactor','Model_te', 'city_te']]

# fit the logistic regression model
logit_model = sm.Logit(y, X).fit()

# print the summary of the model
print(logit_model.summary())

# print the p-values for each coefficient
print(logit_model.pvalues)

# print the R-squared value
print("R-squared: ", logit_model.prsquared)


In [ ]:
import numpy as np
import statsmodels.api as sm

# create a logistic regression model
logit_model = sm.Logit(y, X).fit()

# print the coefficients in the log odds scale
print(logit_model.params)

# exponentiate the coefficients to get the odds ratio interpretation
odds_ratios = np.exp(logit_model.params)
print(odds_ratios)
